# Generated by Django 5.1.4 on 2025-01-16 19:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="license_number",
            field=models.CharField(
                max_length=8,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
        ),
    ]
